### ISSUE TITLE
pyDARN v2.1 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#145]
# Release

**Release number**: v2.1

- [ ] Major - Structural/User interface change
- [x] Minor - New feature or Deprecated feature
- [ ] Patch - bug fixes 

## Scope

The main focus could be `rpos` function plus all the minor changes. 

## Propose Deadline

**Date**: **April 16, 2021**

## Pull Requests

**All PRs merged into `develop` will be included in this release**

### Pull Request To Be Included

**Here is a list of PRs/Issues that need to be merged in still before the release**
- [ ] #108 
- [ ] #50 - if I can get it out by then 
- [ ] #132 - slant range related PRs/Issue this should be an easy solve after the meeting
- [ ] #103 @billetd are you okay with this?
### Pull Requests To not be Included

**Here is a list of PRs/Issues that are not to be merged in before the release branch is released**
- [ ] #144 - Unless @SEC-VT you can do this PR without including Cartopy?
- [ ] #143 - Some of these could be included in the release if they avoid Cartopy

## Details

So here is my proposed game plan, there is a lot of new development happening between Ground Scatter Coordinates and Cartopy. Ground Scatter Coordinates is a minor release. However, because cartopy includes a dependency that can be tricky to install for some and brings in a whole suite of features I was thinking if we focus on cartopy after this release and make it really good with maybe convection plots this could be a major release. Also, separating features we can give better credit to authors developing. 

Thoughts?

**Comment by SEC-VT** [comment]
That works for me! I'll separate the PRs and focus on the cartopy agnostic parts.

**Comment by mts299** [comment]
Thank you @SEC-VT I am very excited about all this work you are doing plus a few future devs coming to pyDARN.

**Comment by SEC-VT** [comment]
So I figured out a way to bypass any cartopy issues that might arise from #143 by simply catching any import exceptions and setting a flag in the plotting routine. I've tested it by uninstalling cartopy and it seems to work well: raising the appropriate errors and such. With that, I'll go ahead and get the PR out today for testing.

**Comment by mts299** [comment]
We don't want to force users to install cartopy if they are not using it, does that make sense?
So throwing an exception may be the opposite of what we want. 

Did you look at my cartopy branch and how I made it an option for setup to install it then we can have checked if the user wants cartopy then import it

**Comment by SEC-VT** [comment]
I gotcha. What I've got tries to import cartopy in the head of the fan.py module, and catches any exceptions (like if the user doesn't have cartopy installed). The normal fan_plot function will work just fine, but if the user tries to plot a cartopy style plot without having the module installed, it throws an exception asking them to either change plotting styles or to install cartopy.
